In [1]:
import numpy as np

a=np.array([[1,2,3]])
b=np.array([[2,3,4]])

result=a+b

print(result)



[[3 5 7]]


In [4]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr=np.ones((1,2))
print(arr)

[[1. 1.]]


In [8]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [12]:
arr=np.linspace(1,5,4)
print(arr)

[1.         2.33333333 3.66666667 5.        ]


In [13]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import random

arr=np.random.randn(1,2)
print(arr)

[[-0.50475079  0.24408333]]


In [17]:
arr=np.random.randint(1, 10, size=(2,3))
print(arr)

[[3 9 2]
 [6 5 3]]


In [20]:
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20])     # shape (2)

result = a + b  # shape (3,3)
print(result)

[[11 21]
 [12 22]
 [13 23]]


In [21]:
data = np.array([[100, 200], [300, 400], [500, 600]])

mean = data.mean(axis=0)
std = data.std(axis=0)

normalized = (data - mean) / std
print(normalized)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [22]:
import numpy as np

scores=np.array([
    [74,81,92],
    [45,88,92],
    [80,70,90]
])

mean=scores.mean(axis=0)
std=scores.std(axis=0)

normalized=(scores-mean)/std
print(normalized)

[[ 0.50166232  0.17996851  0.70710678]
 [-1.39592993  1.12480318  0.70710678]
 [ 0.89426761 -1.30477168 -1.41421356]]


In [23]:
import numpy as np

# Simulated 4x4 grayscale image (pixel values 0-255)
image = np.array([
    [120, 135, 100, 90],
    [80, 150, 200, 175],
    [60, 65, 70, 85],
    [250, 240, 230, 220]
])

# Increase brightness by 30 (clipping to 255)
brighter_image = np.clip(image + 30, 0, 255)

print("Original Image:\n", image)
print("\nBrighter Image:\n", brighter_image)


Original Image:
 [[120 135 100  90]
 [ 80 150 200 175]
 [ 60  65  70  85]
 [250 240 230 220]]

Brighter Image:
 [[150 165 130 120]
 [110 180 230 205]
 [ 90  95 100 115]
 [255 255 255 250]]


In [24]:
import numpy as np

# Sales data for 6 months (in 1000s)
sales = np.array([12, 15, 18, 22, 26, 31])

# Calculate monthly growth
growth = sales[1:] - sales[:-1]

# Percentage growth
percent_growth = (growth / sales[:-1]) * 100

print("Monthly Sales:", sales)
print("Monthly Growth:", growth)
print("Monthly Growth %:", np.round(percent_growth, 2))


Monthly Sales: [12 15 18 22 26 31]
Monthly Growth: [3 3 4 4 5]
Monthly Growth %: [25.   20.   22.22 18.18 19.23]


In [25]:
arr=np.array([1,2,3,4,5,6])
mean=arr.mean(axis=0)
std=arr.std(axis=0)
normalized=(arr-mean)/std
print(normalized)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
