# Part 1 — Beginner Level

# Task 1: Install and Import NumPy

In [1]:
import numpy as np

# Task 2: Create NumPy Arrays

In [2]:
oneDArray=np.array(range(1,11))
TwoDArray=np.array(range(1,10))
TwoDArray=TwoDArray.reshape(3,3)
zerosArray=np.zeros(5)
onesArray=np.ones(5)

In [3]:
print(oneDArray)
print(TwoDArray)
print(zerosArray)
print(onesArray)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


# Task 3: Basic Array Operations


In [4]:
A=[1,2,3,4,5]
B=[5,4,3,2,1]

firstarray=np.array(A)
secondarray=np.array(B)

In [5]:
Addition=(firstarray+secondarray)
Subtracction=(firstarray-secondarray)
Multiplication=(firstarray*secondarray)
Division=(firstarray/secondarray)

In [6]:
print(Addition)
print(Subtracction)
print(Multiplication)
print(Division)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]


# Task 4: Array Information


In [8]:
infoArray=np.array(range(1,21))

In [9]:
shape=infoArray.shape
totalelements=len(infoArray)
datatype=infoArray.dtype

In [10]:
print(shape)
print(totalelements)
print(datatype)

(20,)
20
int64


# Task 5 Indexing

In [11]:
indexingArray=np.array(range(10,80,10))

In [12]:
firstElement=indexingArray[0]
lastElement=indexingArray[-1]
slicingIndex=indexingArray[2:5]

In [13]:
print(firstElement)
print(lastElement)
print(slicingIndex)

10
70
[30 40 50]


# Part 2 :Intermediate Level

# Task 6: Random Arrays


In [14]:
fourbyfourArray=np.array(range(1,17))

In [15]:
fourbyfourArray.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

minvalue=min(fourbyfourArray)
maxvalue=max(fourbyfourArray)
meanvalue=np.mean(fourbyfourArray)

In [17]:
print(minvalue)
print(maxvalue)
print(meanvalue)

1
16
8.5


# Task 7: Reshaping Arrays

In [18]:
reshapingarray=np.array(range(1,13))
reshape3by4=reshapingarray.reshape(3,4)
reshape4by3=reshapingarray.reshape(4,3)

In [19]:
print(reshape3by4)
print(reshape4by3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Task 8: Matrix Operations

In [20]:
matrix1=np.matrix([[1,2,3],[4,5,6]])
matrix2=np.matrix([[1,2,3],[4,5,6]])

In [21]:
addition=matrix1+matrix2
subtraction=matrix1-matrix2
multiplication=np.multiply(matrix1,matrix2)

In [22]:
print(addition)
print(subtraction)
print(multiplication)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]


 # Task 9: Filtering Data


In [23]:
filteringarray=np.array(range(1,31))

In [24]:
greaterthen15=np.where(filteringarray>16)
evenNumbers=np.where(filteringarray%2==0)

In [25]:
print(greaterthen15)
print(evenNumbers)

(array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),)
(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]),)


#  Task 10: Practical Problem

In [26]:
marks = np.array([70, 85, 90, 60, 75, 88, 92, 55, 80, 77])


print("Highest marks:", np.max(marks))


print("Lowest marks:", np.min(marks))


avg = np.mean(marks)
print("Average marks:", avg)


print("Above average:", marks[marks > avg])

Highest marks: 92
Lowest marks: 55
Average marks: 77.2
Above average: [85 90 88 92 80]
