In [1]:
print("day2 of numpy learning")

day2 of numpy learning


In [4]:
import numpy as np

arr1d=np.array([[1,2,3],[4,5,6]])
print(arr1d)

[[1 2 3]
 [4 5 6]]


In [6]:
arr=np.full((2,2),10)
print(arr)

[[10 10]
 [10 10]]


In [7]:
arr1d=np.array([1,2,3])

In [8]:
print(arr1d[0])

1


In [9]:
for item in arr1d:
    print(item)

1
2
3


In [13]:
names=[["asad","basit","majid"],[1,2,3]]
arr=np.array(names)
print(arr[0][1])

basit


In [14]:
for x in arr:
    for y in x:
        print(y)

asad
basit
majid
1
2
3


In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[::1])

[10 20 30 40 50]


In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[:2, :])
print(arr2d[:, :1])

[[1 2 3]
 [4 5 6]]
[[1]
 [4]
 [7]]


In [32]:
arr=np.arange(1,17).reshape(4,4)
print(arr[:2 ,:3])


[[1 2 3]
 [5 6 7]]


In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

shape=np.shape(arr2d)
print(shape)

(3, 3)


In [35]:
flat = np.array([1, 2, 3, 4, 5, 6])
shape=np.shape(flat)
reshape=flat.reshape(2,3)

print(reshape)

[[1 2 3]
 [4 5 6]]


In [37]:
img = np.arange(64).reshape(8, 8)
print(img)
img_flat=img.reshape(-1)
print(img_flat)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]


In [39]:
arr = np.array([[1, 2], [3, 4]])

for row in arr:
    print(row)

for val in arr.flat:
    print(val)

[1 2]
[3 4]
1
2
3
4


In [43]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

joined=np.vstack([a,b])
print(joined)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[9], [10]])
c=np.array([[5,6],[7,8]])

joined=np.hstack([a,b,c])
print(joined)

[[ 1  2  9  5  6]
 [ 3  4 10  7  8]]


In [48]:
print(np.concatenate((a, b), axis=1) )

[[ 1  2  9]
 [ 3  4 10]]


In [53]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vertical=np.hsplit(matrix,3)
print(vertical)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [56]:
data = np.array([[i] for i in range(100)])
train, test = np.array_split(data, 2)
# print(train)
print(test)

[[50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]
 [68]
 [69]
 [70]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [77]
 [78]
 [79]
 [80]
 [81]
 [82]
 [83]
 [84]
 [85]
 [86]
 [87]
 [88]
 [89]
 [90]
 [91]
 [92]
 [93]
 [94]
 [95]
 [96]
 [97]
 [98]
 [99]]


In [64]:
arr=np.array([1,2,3,4,5])
idx=np.where(arr>3)
arr1=np.array(idx)

print("idx",idx)

IndexError: invalid index to scalar variable.

In [68]:
arr = np.array([40, 10, 50, 20])
sorted_arr = np.sort(arr)

print(sorted_arr)

TypeError: sort() got an unexpected keyword argument 'reversed'

In [69]:
arr2d = np.array([[3, 1, 2], [6, 4, 5]])
sorted_rows = np.sort(arr2d, axis=1)


In [70]:
print(sorted_rows)

[[1 2 3]
 [4 5 6]]


In [71]:
probs = np.array([0.1, 0.6, 0.2, 0.8])
top_class = np.argmax(probs)
print(top_class)


3


In [76]:
data = np.array([10.15, 15.15, 20.15, 25.15, 30.15],dtype=int)

filtered=data[data>20.15]

print(filtered.dtype)

int64


In [78]:
a = np.array([1, 2, 3])
b=a.view()
b[0]=99
print(a)
print(b)

[99  2  3]
[99  2  3]


In [84]:
probs = np.array([0.15, 0.85, 0.60, 0.05, 0.40, 0.75])
filtered=probs[probs>0.5]
sorted_filtered=np.sort(filtered)[::-1]


top_indexes = np.where(probs > 0.5)

print("Filtered High Confidence:", filtered)
print("Sorted:", sorted_filtered)
print("Class Indexes:", top_indexes)

Filtered High Confidence: [0.85 0.6  0.75]
Sorted: [0.85 0.75 0.6 ]
Class Indexes: (array([1, 2, 5]),)


In [102]:
import numpy as np

# Step 1: Create the Dataset
features = np.array([
    [100, 1, 5],
    [220, 0, 2],
    [45, 10, 20],
    [30, 5, 15],
    [150, 1, 1],
    [20, 8, 30],
])
labels = np.array([0, 0, 1, 1, 0, 1])

# Step 2: Normalize Features
mean = features.mean(axis=0)
std = features.std(axis=0)
normalized_features = (features - mean) / std

# print(normalized_features)

# # Step 3: Filter Out Low-Quality Samples (< 40 words)
# mask = features[:, 0] >= 40
# filtered_features = normalized_features[mask]
# print(filtered_features)
# filtered_labels = labels[mask]
# print(filtered_labels)

# # Step 4: Shuffle Data
# combined = np.hstack((filtered_features, filtered_labels.reshape(-1, 1)))
# print(combined)
# print(np.random.seed(42))

# print(np.random.shuffle(combined))
shuffled_features = combined[:, :-1]
print(shuffled_features)
shuffled_labels = combined[:, -1].astype(int)
print(shuffled_labels)


# # Step 5: Train-Test Split (70% Train, 30% Test)
split_idx = int(0.7 * len(shuffled_features))
print(split_idx)
X_train = shuffled_features[:split_idx]
print(X_train)
# y_train = shuffled_labels[:split_idx]
# X_test = shuffled_features[split_idx:]
# y_test = shuffled_labels[split_idx:]

# # Bundle all steps for the notebook
# steps = {
#     "Original Features": features,
#     "Original Labels": labels,
#     "Normalized Features": normalized_features,
#     "Filtered Features": filtered_features,
#     "Filtered Labels": filtered_labels,
#     "Shuffled Features": shuffled_features,
#     "Shuffled Labels": shuffled_labels,
#     "X_train": X_train,
#     "y_train": y_train,
#     "X_test": X_test,
#     "y_test": y_test
# }

# steps.keys()  # Showing available data objects for export


[[ 1.75002638 -1.09526989 -0.96437415]
 [ 0.77650177 -0.83240511 -1.05923062]
 [ 0.08112705 -0.83240511 -0.67980473]
 [-0.68378514  1.53337784  0.74304238]]
[0 0 0 1]
2
[[ 1.75002638 -1.09526989 -0.96437415]
 [ 0.77650177 -0.83240511 -1.05923062]]


In [112]:
arr=np.array([10,20,20,30,40,40])
filtered=arr[arr>20]
mean=np.mean(arr)
std=np.std(arr)
print(std)
print(mean)

normalize=(arr-mean)/std
print(normalize)

sorted_arr=np.sort(arr)
print(sorted_arr)
      

11.055415967851333
26.666666666666668
[-1.50755672 -0.60302269 -0.60302269  0.30151134  1.20604538  1.20604538]
[10 20 20 30 40 40]
