In [1]:
# python is dynamically typed languague the type is decided at runtime

In [2]:
# we have two varibales and we want to swap them without using temp variable

In [5]:
a=10
b=20

a,b=b,a
print(b,a)

10 20


In [6]:
a = 10
b = a
a = 20

In [7]:
print(b)

10


In [8]:
True or print("Hello")

True

In [12]:
x = [1,2,3]
y = x
y.append(4)
print(x)

x=2

[1, 2, 3, 4]


In [13]:
result="even" if x % 2==0 else "odd"

In [14]:
print(result)

even


In [15]:
if x%2==0:
    result="even"
    print(result)
else:
    result="odd"
    print(result)

    

even


In [16]:
result="Even" if x%2==0 else "odd"

In [17]:
print(result)

Even


In [23]:
number="positive" if x>0 else  "Neutral"

print(number)

positive


In [24]:
for i in range(5):
    if i == 10:
        break
else:
    print("Completed")

Completed


In [25]:
for i in range(10):
    if i==10:
        break
    else:
        print("completed")

completed
completed
completed
completed
completed
completed
completed
completed
completed
completed


In [27]:
print("i love myself")

i love myself


In [51]:
# we have to create dictionary and we have to find average

marks={
    "Ali":87,
    "Asad":92,
    "Saqib":98
}

marks=(marks.values())
average_marks=sum(marks)/len(marks)
print(average_marks)


Highest_score=max(marks)
print(Highest_score)
# print(f"the student with the highest score is {marks.key()} {Highest_score}")

92.33333333333333
98


In [52]:
for val,mark in marks.items():
    if val>80:
        print("pass")
    else:
        print("fail")

AttributeError: 'dict_values' object has no attribute 'items'

In [49]:
for name, mark in marks.items():
    if mark >= 50:
        print(name, "→ Pass")
    else:
        print(name, "→ Fail")

AttributeError: 'dict_values' object has no attribute 'items'

In [ ]:
while True:
    number1 = int(input("Enter number 1: "))
    number2 = int(input("Enter number 2: "))
    operator = input("Enter operator (+, -, *, /): ")

    if operator == "+":
        print("Result:", number1 + number2)
    elif operator == "-":
        print("Result:", number1 - number2)
    elif operator == "*":
        print("Result:", number1 * number2)
    elif operator == "/":
        if number2 != 0:
            print("Result:", number1 / number2)
        else:
            print("Cannot divide by zero")
    else:
        print("Invalid operator")

    choice = input("Do you want to continue? (yes/no): ").lower()

    if choice != "yes":
        print("Calculator closed.")
        break

enter number 1 10
enter number 2 20
enter any operator you want to perform 30
enter any choice yes


In [ ]:
while True:
    number1 = int(input("Enter number 1: "))
    number2 = int(input("Enter number 2: "))
    operator = input("Enter operator (+, -, *, /): ")

    if operator == "+":
        print(number1 + number2)
    elif operator == "-":
        print( number1 - number2)
    elif operator == "*":
        print( number1 * number2)
    elif operator == "/":
        if number2 != 0:
            print( number1 / number2)
        else:
            print("Cannot divide by zero")
    else:
        print("Invalid operator")

    choice = input("Do you want to continue? (yes/no): ").lower()

    if choice != "yes":
        print("Calculator closed.")
        break

In [6]:
sentence = "doctor on duty sees doctor patients and doctor prescribes medicine"

words=sentence.split()
print(words)

freq={}

for word in words:
    freq[word]=freq.get(word,0)+1

print(freq)




print("Word Frequencies:")
for word, count in freq.items():
    print(f"{word}: {count}")

['doctor', 'on', 'duty', 'sees', 'doctor', 'patients', 'and', 'doctor', 'prescribes', 'medicine']
{'doctor': 3, 'on': 1, 'duty': 1, 'sees': 1, 'patients': 1, 'and': 1, 'prescribes': 1, 'medicine': 1}
Word Frequencies:
doctor: 3
on: 1
duty: 1
sees: 1
patients: 1
and: 1
prescribes: 1
medicine: 1


In [8]:
catalog = {"apple": 50, "banana": 20, "orange": 30, "mango": 40}

print(catalog)

cart={}
cart["apple"] = 3   # 3 apples
cart["mango"] = 2   # 2 mangoes

# Update quantity if adding more
cart["apple"] += 1   # add 1 more apple

# Calculate total bill
total = 0
print("\n--- BILL ---")
for item, qty in cart.items():
    price = catalog[item] * qty
    total += price
    print(f"{item.capitalize()} x {qty} = {price}")

{'apple': 50, 'banana': 20, 'orange': 30, 'mango': 40}

--- BILL ---
Apple x 4 = 200
Mango x 2 = 80


In [9]:
evenSquared={x: x**2 for x in range(1,11) if x%2==0}

In [10]:
print(evenSquared)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100}


In [11]:
oddSquared={x:x**2 for x in range(1,11) if x%2!=0}

In [12]:
print(oddSquared)

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}


In [14]:
multiplesOF5={x for x in range(1,11) if x%5==0}
print(multiplesOF5)

{10, 5}


In [18]:
for x in range(1,11):
    print(f"{x}*{2}={x*2}")

1*2=2
2*2=4
3*2=6
4*2=8
5*2=10
6*2=12
7*2=14
8*2=16
9*2=18
10*2=20


In [20]:
a=10
b=20
a,b=b,a
print(b,a)

10 20


In [21]:
string="123"
integer=int(string)
floating=float(string)
print(integer)
print(floating)

123
123.0


In [24]:
a=bin(100)
print(a)

b=oct(100)
print(b)

c=hex(100)
print(c)

0b1100100
0o144
0x64


In [42]:
# find second largest element in string

list1=[1,2,3,4,5,6,1,2,1,2]
maxhighest=max(list1)
print(maxhighest)


uniqueList=list(set(list1))
print(uniqueList)


list2=[10,12,14,15]

list1.extend(list2)
print(list1)

list1.sort()
print(list1)


someNumbers=[x for x in range(0,9) if x%2==0]

print(someNumbers)


tuple1=(1,2,3,4,5)
print(tuple1[-1])

set1={"asad","basit","majid"}
set2={"asad","basit","majid"}

print(type(set1))
checking=set1.issubset(set2)
print(checking)



listofwords=["Asad","asad","Asad","Asad"]

freq={}

for word in listofwords:
    freq[word]=freq.get(word,0)+1

print(freq)

6
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 1, 2, 1, 2, 10, 12, 14, 15]
[1, 1, 1, 2, 2, 2, 3, 4, 5, 6, 10, 12, 14, 15]
[0, 2, 4, 6, 8]
5
<class 'set'>
True
{'Asad': 3, 'asad': 1}


In [47]:
items1={"fruit":50,"biscuit":20}

highestvalue=max(items1.values())
print(highestvalue)


50


In [48]:
import numpy as np

In [49]:
np.mean([10,20,30,40])

np.float64(25.0)

In [50]:
ar=np.array([1,2,3,4,5,6])
print(type(ar))

<class 'numpy.ndarray'>


In [59]:
ar=np.array([1,2,3,4,5,6,6.0,"Asad","usman","Basit"])
print(ar)

['1' '2' '3' '4' '5' '6' '6.0' 'Asad' 'usman' 'Basit']


In [62]:
li=[1,2,3,4,5,6]

listsquared=[x**2 for x in li ]
arr=np.array(li)
print(arr**2)

[ 1  4  9 16 25 36]


In [61]:
print(listsquared)

[1, 4, 9, 16, 25, 36]


In [66]:
arr=np.array(range(0,19),ndmin=3)


In [68]:
print(arr.ndim)

3


In [77]:
arrofzeros=np.ones((1))

In [78]:
print(arrofzeros)

[1.]


In [79]:
r = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]
l = np.linspace(0, 1, 5) 

In [80]:
print(r)
print(l)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [91]:
arr=np.array([[1,2,3,4,5,6],[1,2,3,4,4,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

print(arr**2)

(2, 6)
2
12
int64
8
[[ 1  4  9 16 25 36]
 [ 1  4  9 16 16 36]]


In [93]:
a = np.arange(6)      # [0 1 2 3 4 5]

# Reshape
b = a.reshape((2, 3))

flat = b.ravel()

print(b)

print(flat)


[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [94]:
arr = np.arange(10)
mask = (arr % 2 == 0)
print(arr[mask])  # [0 2 4 6 8]

[0 2 4 6 8]


In [96]:
print(np.random.rand(3,3))  # Uniform [0,1]
print(np.random.randn(3,3)) # Normal distribution
print(np.random.randint(0, 10, size=(3,3)))

[[0.91201718 0.46158104 0.04141762]
 [0.08765849 0.36948911 0.51830264]
 [0.30467831 0.68331285 0.28366954]]
[[ 0.30642619 -0.66881831 -1.56550725]
 [ 0.84307625 -0.48711171 -1.099559  ]
 [-0.58262233  0.34295873 -1.49856329]]
[[5 4 9]
 [7 6 0]
 [4 1 7]]


In [99]:
data = np.random.randn(1000)
print(data)
data[data > 2] = 2  # Clipping outliers

[ 4.70292738e-01  8.49711196e-01 -1.63664022e+00  1.31746730e+00
 -2.92442461e-01 -1.61535874e+00  1.21432722e+00  1.05880545e-01
  4.98855837e-01  8.83046415e-02 -1.37091367e+00 -2.19445177e+00
 -2.12781275e-01  1.76334746e+00 -7.84716982e-01 -3.61398246e-01
 -4.49713993e-02  2.51250902e-01  3.10372204e-01 -3.24040245e-01
 -5.70620768e-01  4.15485692e-01  2.22252588e-01  2.61652466e-01
 -1.18404904e+00 -1.11850105e+00  7.61713720e-01 -1.47021141e+00
 -4.09740339e-01  9.47323706e-01  3.48151673e-01  1.15326610e-01
 -4.18152653e-02 -5.36902977e-01 -2.58591020e-02  7.79017651e-01
  1.39585260e+00  2.23986035e+00  7.42973955e-01 -1.35173230e+00
  5.99497520e-01 -1.24689606e+00 -1.47851173e+00  8.14184988e-01
  1.37731418e+00  8.32874808e-01 -6.74364405e-01 -8.74922626e-01
  4.74831991e-01  5.32558246e-02  1.03504129e+00 -1.96452037e+00
  7.33618517e-02 -5.94093744e-01 -2.69436513e-01  7.97659012e-01
 -2.12847407e-01  8.09725900e-01  3.56330695e-01 -6.10789992e-01
 -2.21367358e-01  1.60561

In [98]:
print(data)

[ 7.26444221e-02  1.58860615e-01  9.12834296e-01  5.35655551e-01
 -2.52405606e-01  4.36108433e-01 -1.91067122e+00 -1.02277088e+00
 -1.63004828e+00 -8.42225613e-01 -2.03690393e+00  1.03034603e+00
  4.66277531e-01 -4.68696605e-01 -1.57380000e+00 -6.14473729e-02
  1.38309465e-01  1.09940588e+00  4.90869376e-01  6.01038101e-01
 -1.64396931e-01  3.35816862e-01  9.53518546e-01 -1.79287699e-01
  1.79793695e-01  3.70791338e-01 -4.20913354e-01 -1.24415565e+00
  1.06952073e+00  3.02091478e-01  5.04624149e-01  2.00000000e+00
  3.73936799e-01  6.31998473e-01  1.58674885e+00 -8.25414963e-01
  4.06910127e-01 -2.72242743e-01 -8.61517701e-02 -2.25428585e+00
  1.08764362e-02 -9.58849205e-01  1.01846237e+00  7.39649132e-01
 -1.59081830e+00 -3.91789056e-01  7.36685569e-01  9.76998336e-01
  3.55480627e-02 -3.21085497e-01  1.46438045e+00 -9.73612393e-01
  1.54938397e-01  3.46358172e-01 -3.78073159e-01 -2.94534787e-02
 -1.07069910e-01 -5.69220226e-01  1.91219697e-01  6.89994262e-02
  1.72108849e+00 -2.08936

In [101]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [108]:
print(data[0,:])

[10 20 30]


In [113]:
print(data[data>50]) # [60 70 80 90]
print(data[data>30])

[60 70 80 90]
[40 50 60 70 80 90]


In [115]:
matrix = np.array([[1,2,3],[4,5,6]])

print(np.sum(matrix,axis=1))

[ 6 15]


In [116]:
data = np.array([10, 20, 30, 40])
normalized = (data - np.mean(data)) / np.std(data)

In [117]:
print(normalized)

[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [119]:
sales = np.array([100, 150, 200])
np.cumsum(sales)

array([100, 250, 450])

In [120]:
values = np.array([80, 90, 100])
weights = np.array([0.2, 0.3, 0.5])
np.average(values, weights=weights)  

np.float64(93.0)